### PR TITLE
add 2020_Margaryan_Viking

### LINKED ISSUE #15: 2020_Margaryan_Viking
## Check for existing package
I have checked the following places for the requested package and could not find it:

- [x] Poseidon Package Directory
- [x] The `packages/` directory in this repository
- [x] Open issues in this repository
- [x] Open pull requests in this repository

 confirmed

## Required information for the package

- DOI of publication: https://doi.org/10.1038/s41586-020-2688-8 <- Please replace this example DOI with the one for the relevant publication
- Project accession number: [PRJEB37976](https://www.ebi.ac.uk/ena/browser/view/PRJEB37976) <- Please replace this example ENA project link with the one for the relevant publication

## Will you work on this?

If you are planning to work on comppiling the `.ssf` file required to add this package, please assign yourself to this issue.
This helps the community collaborate effectively and avoid duplicating work.

### PR DESCRIPTION
**Pull request by gagr88**
Closes #15  

## PR Checklist
- [x] The PR contains a sequencingSourceFile (`.ssf`) for the package. 
- [x] The name of the `.ssf` file(s) matches the package name (i.e. `packages/2023_my_package/2023_my_package.ssf`).
- [x] Comment `@delphis-bot create backbone` to this pull request to awaken Poseidon's trusty helper. (This should be repeated whenever changes are made to the SSF file contents).

This will add a number of files to the PR. Check that they are all there:
- [x] `packages/{package_name}/{package_name}.tsv` was added to the PR.
- [x] `packages/{package_name}/{package_name}.tsv_patch.sh` was added to the PR from template.
- [x] `packages/{package_name}/script_versions.txt` was added to the PR.
- [x] `packages/{package_name}/{package_name}.config` was added to the PR from template.

### Package SSF file (`*.ssf`)
  - [x] I confirm that the `poseidon_IDs`, `udg`, and `library_built` are filled and correct.
  - [x] I made sure to leave `notes` where necessary to explain any special cases/judgement calls made for data entries.

### Package TSV file (`*.tsv`)
  - [x] I confirm that the `UDG`, `Strandedness` columns are correct for each library.
  - [x] I confirm that the `R1_target_file` and `R2_target_file` columns point to the correct FastQ files for the library (i.e. consistent with SSF file).

### Package config file (`*.config`)
The template config file includes a few TODO statements, and information about them. Please ensure that you:
  - [x] I have selected the appropriate config for the CaptureType of the package.
  - [x] If any nf-core/eager parameters need to be altered from their defaults, I have added them within the `params` section at the end of the package config file.

### CODE REVIEW

**Comment by gagr88** [comment]
@delphis-bot create backbone

**Comment by TCLamnidis** [comment]
Thank you for submitting data to poseidon-eager!
Could you fix the name of the files and package? It should be `2020_Margaryan_Viking`.

**Comment by gagr88** [comment]
> 

I have no idea how to change the name

**Comment by TCLamnidis** [comment]
The automatic SSF file validation had some growing pains, but all clear now. Will review and merge shortly.

**Review by TCLamnidis — APPROVED** [review]
The library names being `unspecified` is not ideal, but it _is_ what is on the ENA, so it's fair to leave them like that.

**Pull request merged**
